title: "AM215: Advanced Scientific Computing"
author: "Harvard University"
copyright: "2025"

only_build_toc_files: true

execute:
  execute_notebooks: off
  cache: "_build/.jupyter_cache"
  
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

html:
  theme: sphinx-book-theme
  title: "AM215 Course Materials"
  
latex:
  latex_documents:
    targetname: am215-complete.tex

exclude_patterns: ['.git/*', '.direnv/*']
