# pyproject.toml - For uv users (modern Python package management)
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "am215-course-materials"
version = "0.1.0"
description = "AM215: Advanced Scientific Computing Course Materials"
authors = [
    {name = "Harvard University", email = "your-email@harvard.edu"},
]
dependencies = [
    # Core MyST tools
    "jupyter-book>=0.15.1",
    "myst-parser>=2.0.0",
    "myst-nb>=0.17.0",
    "sphinx>=6.0.0",
    "sphinx-book-theme>=1.0.0",
    "sphinx-external-toc>=0.3.0",
    
    # Scientific computing
    "numpy>=1.24.0",
    "matplotlib>=3.6.0",
    "scipy>=1.10.0",
    "sympy>=1.12.0",
    "pandas>=2.0.0",
    "seaborn>=0.12.0",
    "plotly>=5.14.0",
    
    # Jupyter ecosystem
    "jupyter>=1.0.0",
    "jupytext>=1.14.0",
    "ipykernel>=6.20.0",
    "ipywidgets>=8.0.0",
    
    # Development tools
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
    
    # Additional useful packages
    "requests>=2.28.0",
    "pyyaml>=6.0.0",
    "watchdog>=3.0.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=3.0.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/your-org/am215-materials"
Repository = "https://github.com/your-org/am215-materials"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["am215"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

# requirements.txt - For venv users (traditional approach)
# Core MyST tools
jupyter-book>=0.15.1
myst-parser>=2.0.0
myst-nb>=0.17.0
sphinx>=6.0.0
sphinx-book-theme>=1.0.0
sphinx-external-toc>=0.3.0

# Scientific computing
numpy>=1.24.0
matplotlib>=3.6.0
scipy>=1.10.0
sympy>=1.12.0
pandas>=2.0.0
seaborn>=0.12.0
plotly>=5.14.0

# Jupyter ecosystem
jupyter>=1.0.0
jupytext>=1.14.0
ipykernel>=6.20.0
ipywidgets>=8.0.0

# Development tools
black>=23.0.0
isort>=5.12.0
flake8>=6.0.0
mypy>=1.0.0

# Additional useful packages
requests>=2.28.0
pyyaml>=6.0.0
watchdog>=3.0.0

# requirements-dev.txt - Additional development dependencies
pre-commit>=3.0.0
pytest>=7.0.0
pytest-cov>=4.0.0