# _config.yml

# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "AM 215: Mathematical Modeling for Computational Science"
author: "" # Add your author name here if you wish

# -----------------------------------------------------------------------------------
# Settings for notebook execution
# -----------------------------------------------------------------------------------
execute:
  execute_notebooks: auto  # Can be "auto", "force", "off", or "cache"

# -----------------------------------------------------------------------------------
# Settings for the book's repository and launch buttons
# This is the correct way to configure Colab, Binder, and other launch services.
# -----------------------------------------------------------------------------------
repository:
  url: https://github.com/Harvard-AM215/book  # From your project.github key
  path_to_book: jupyter-book      # The path from your repository root to your book's root (where this file is)
  branch: main          # The branch your book is hosted on (main, master, etc.)

# Add the launch buttons that should appear on each notebook page.
launch_buttons:
  colab_url: "https://colab.research.google.com"  # This enables the Colab button
  thebe: true  # This enables the rocket icon for live code cells

# --- Sphinx Configuration ---
# This new block passes settings directly to the underlying Sphinx build process.
sphinx:
  config:
    # This is the configuration dictionary for sphinx-thebe
    thebe_config:
      # This is the magic switch that tells Thebe to use Pyodide
      use_lite_kernel: true
      
      # These are still needed so Thebe knows where to find your content
      # if it ever needs to fall back or fetch files.
      repository_url: "https://github.com/Harvard-AM215/book"
      repository_branch: main
      path_to_book: jupyter-book
