name: Deploy AM215 Book

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync
    
    - name: Create paired notebooks from MyST files
      run: |
        echo "Creating notebooks from MyST files..."
        # Method 1: Try with config file first
        if uv run jupytext --sync content/**/*.md 2>/dev/null; then
          echo "✅ Used jupytext.toml config"
        else
          echo "⚠️ Config failed, using manual conversion..."
          # Method 2: Manual conversion without config
          find content -name "*.md" -type f | while read file; do
            if [[ -f "$file" ]]; then
              echo "Converting $file..."
              uv run jupytext --to notebook --output "${file%.md}.ipynb" "$file" || echo "Failed to convert $file"
            fi
          done
        fi
        
        # List created notebooks
        echo "Created notebooks:"
        find content -name "*.ipynb" -type f
    
    - name: Cache Jupyter execution
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('content/**/*.md', 'content/**/*.ipynb') }}
        restore-keys: |
          jupyter-book-cache-
    
    - name: Build book with execution
      run: |
        echo "Building Jupyter Book 2.x with execution..."
        uv run jupyter-book build . --all
      env:
        # Ensure proper execution environment
        JUPYTER_CACHE: "_build/.jupyter_cache"
    
    - name: Upload build artifacts (for debugging)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          _build/
          !_build/html/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        # Include .ipynb files for Colab links
        exclude_assets: '.nojekyll'
