name: deploy-book

# Run this when the main branch changes, but only on changes inside the book's folder.
on:
  push:
    branches:
    - main
    paths:
    - 'jupyter-book/**'
    - '.github/workflows/deploy-book.yml' # Also re-run if the workflow itself changes

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Required to deploy to GitHub Pages
      id-token: write   # Required to authenticate with GitHub Pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Cache the global uv cache
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-cache-${{ hashFiles('**/pyproject.toml') }}

    - name: Install dependencies with uv sync
      run: |
        pip install uv
        # Use `uv sync` to create an exact, reproducible environment from pyproject.toml.
        # This is the idiomatic way to build environments for CI.
        uv sync

    # (optional) Cache your executed notebooks between runs
    - name: Cache executed notebooks
      uses: actions/cache@v4
      with:
        path: jupyter-book/_build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('**/pyproject.toml') }}

    # Build the book, targeting the correct subdirectory
    - name: Build the book
      run: |
        uv run jupyter-book build jupyter-book

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "jupyter-book/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
